# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30ccb090069839f2813e3c3c903948ff333d028bb556e23038fba5f37e81a61b57f73356232d623d392e0da24199ff08606da1bb410918d5bcb72cd2e32c18fa

test:
  secret_key_base: 9992520b98e17d0a4ce39af83fe701508492053077c3f4643bf1400236b0a43f0e3abf507e8bafca11894406cb0a2904d6ed79ab5eac54272f4250439e706b26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
