# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff1492e3b9418d712579a8572839044467f72613d7394f09844bcbc1f9a34fcc14407f05c9e8ad97b448cc08d97c6cca71ae1818f1810bf556695e3e4f574d36

test:
  secret_key_base: 1eb4114a5fe41f60da585b151d6dfc46206a05cd34a6b2db146051356d6fd18cf1ef4fd91cd9da5724f3d3851d0bb9e30a67baffd04f4575179a9a30a87f9d89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
